### ISSUE TITLE
Can't get kosher food in Washington DC

### ISSUE THREAD

**Issue by navteniev** [CSC59939/LunchIn#47]
Tried to get some kosher food in Washington DC and got a map of the ocean
<img width="1033" alt="screen shot 2018-11-14 at 8 00 15 pm" src="https://user-images.githubusercontent.com/619960/48522941-6e436500-e848-11e8-96bb-13cd3220ff6f.png">

**Comment by buenoluis007** [comment]
Fixed in #60.
