### ISSUE TITLE
Too many characters 

### ISSUE THREAD

**Issue by mjacome0** [CSC59939/LunchIn#49]
You might want to limit the amount of characters allowed in the food section. 

<img width="1440" alt="screen shot 2018-11-14 at 8 03 04 pm" src="https://user-images.githubusercontent.com/31998189/48523010-a5197b00-e848-11e8-8661-fb563ea7d315.png">

**Comment by sengfung27** [comment]
Hours spent: 1 hour

- Maximum 20 characters
