### ISSUE TITLE
Improper Firebase Imports

### ISSUE THREAD

**Issue by ayushyamitabh** [CSC59939/LunchIn#53]
Here's how to do it properly:
```jsx
import firebase from 'firebase/app';
import 'firebase/auth'; // change auth to whatever module you want to import
```

![image](https://user-images.githubusercontent.com/26289557/48523306-e199a680-e849-11e8-8d6c-00d22dcf39da.png)

**Comment by sengfung27** [comment]
Hours spent: 30 minutes

- import only needed package from firebase
