### ISSUE TITLE
Yelp generate all businesses instead of just restaurants

### ISSUE THREAD

**Issue by gerryzqx** [CSC59939/LunchIn#71]
![screen shot 2018-11-24 at 10 25 50 am](https://user-images.githubusercontent.com/14956377/48969907-6798b880-efd3-11e8-9d32-981b820d4daa.jpg)

If "apple" is a food being generated, it generates the actual apple store instead of restaurants that has the apple food.

**Comment by chc5** [comment]
I've fixed this on my own branch. However, I see major inconsistencies between Google Maps and Yelp. These two services categorizes restaurants differently. (e.g. a deli is considered a restaurant to Maps while Yelp doesn't consider a deli as a restaurant).

Thus, we have to use the results from Google Maps instead.

**Comment by gerryzqx** [comment]
@chc5 Yes, I think using the results from Google Maps would be better. Thanks for addressing the problem you ran into with us. @EvanVasquez @buenoluis007 work with @chc5 to get the results from google maps and pass it to yelp.

**Comment by gerryzqx** [comment]
Fixed in Pull Request #87
