### ISSUE TITLE
Mock Disaster Recovery Scenarios

### ISSUE THREAD

**Issue by sengfung27** [CSC59939/LunchIn#78]
Purpose
- To expose to a simulated disaster event, and to come out with a recovery plans.

Process
- Work together with teammates, respond to events based on continuity knowledge.

Scenarios

1. The quota of requesting a Yelp's review API is exceeded.

How do we know 
1. Heroku's monitoring tools detects failure requests.
2. Receive email notifications when an alert is triggered.

Solution
- Using another billing info ( *Note: not sure if it's going to work )

**Comment by gerryzqx** [comment]
@sengfung27 Since we will mock the disaster by making yelp run out of quota, will Heroku's monitoring tool be able to detect the failure from yelp?

**Comment by chc5** [comment]
I'm not sure about the monitoring, but Heroku will definitely output the error in the logs.

**Comment by gerryzqx** [comment]
Oh ok, got it. Thanks!

**Comment by chc5** [comment]
Successfully increased the number of requests we can make to Yelp using multiple API Keys. In total, our app can handle 1500 requests and we can scale up if necessary.
