### ISSUE TITLE
Display neareast restaruant (google maps)

### ISSUE THREAD

**Issue by zhuoyingcai** [CSC59939/LunchIn#8]

**Comment by buenoluis007** [comment]
Saturday 11/4/18 (Evan): Got Geocode to pull latitude and longitude from the users address.
Hours 3

**Comment by buenoluis007** [comment]
Sunday 11/5/18 (Luis): Put Geocode into googleMaps.js, and fixed up super messy code that was bad at making the google maps component reload on food generation. It now reloads based on the random food. Got latest version of master to work with our branch, and fixed a small big where the google maps component loaded over the Yelps review component.
Hours 4

**Comment by buenoluis007** [comment]
Monday 11/6/18 (Luis): Created a jest test for the google maps component. Also merged latest master into branch and resolved conflicts. Google Maps API key is now being pulled from .env and is no longer publicly visible.
Hours: 3
